### ISSUE TITLE
Invalid value for shared scalar at /opt/freeradius-oauth2-perl/main.pm line 361

### ISSUE THREAD

**Issue by andisgithub** [jimdigriz/freeradius-oauth2-perl#15]
Hi!

I'm trying to authentificate wireless users using EAP-TTLS/PAP via freeradius-oauth2-perl.

radtest myuser@mydomain.onmicrosoft.com mypassword 127.0.0.1 0 RadiusSecret works fine and results with Access-Accept

When trying to autheniticate wireless user the request is routed to inner-tunnell where it fails 

(5)   # Executing group from file /etc/freeradius/sites-enabled/inner-tunnel
(5)     Auth-Type oauth2 {
(5)       policy oauth2.authenticate {
(5) oauth2_perl:   $RAD_REQUEST{'User-Name'} = &request:User-Name -> 'myuser@mydomain.onmicrosoft.com'
(5) oauth2_perl:   $RAD_REQUEST{'User-Password'} = &request:User-Password -> 'mypassword'
(5) oauth2_perl:   $RAD_REQUEST{'FreeRADIUS-Proxied-To'} = &request:FreeRADIUS-Proxied-To -> '127.0.0.1'
(5) oauth2_perl:   $RAD_CHECK{'Auth-Type'} = &control:Auth-Type -> 'oauth2'
(5) oauth2_perl:   $RAD_CONFIG{'Auth-Type'} = &control:Auth-Type -> 'oauth2'
rlm_perl: oauth2 authenticate
Use of uninitialized value $realm in hash element at /opt/freeradius-oauth2-perl/main.pm line 361.
Use of uninitialized value $realm in hash element at /opt/freeradius-oauth2-perl/main.pm line 361.
Use of uninitialized value $realm in hash element at /opt/freeradius-oauth2-perl/main.pm line 361.
(5) oauth2_perl: perl_embed:: module = /opt/freeradius-oauth2-perl/main.pm , func = authenticate exit status= Invalid value for shared scalar at /opt/freeradius-oauth2-perl/main.pm line 361.
(5) oauth2_perl: &request:User-Password = $RAD_REQUEST{'User-Password'} -> 'mypassword'
(5) oauth2_perl: &request:User-Name = $RAD_REQUEST{'User-Name'} -> 'myuser@mydomain.onmicrosoft.com'
(5) oauth2_perl: &request:FreeRADIUS-Proxied-To = $RAD_REQUEST{'FreeRADIUS-Proxied-To'} -> '127.0.0.1'
(5) oauth2_perl: &control:Auth-Type = $RAD_CHECK{'Auth-Type'} -> 'oauth2'
(5)         [oauth2_perl] = fail
(5)       } # policy oauth2.authenticate = fail
(5)     } # Auth-Type oauth2 = fail
(5)   Failed to authenticate the user
(5)   Using Post-Auth-Type Reject
(5)   Post-Auth-Type sub-section not found.  Ignoring.
(5)   # Executing group from file /etc/freeradius/sites-enabled/inner-tunnel
(5)   Login incorrect: [andis1@jnedu.onmicrososft.com] (from client andis1 port 0 via TLS tunnel)
(5) } # server inner-tunnel
(5) Virtual server sending reply
(5) eap_ttls: Got tunneled Access-Reject
(5) eap: ERROR: Failed continuing EAP TTLS (21) session.  EAP sub-module failed
(5) eap: Sending EAP Failure (code 4) ID 6 length 4
(5) eap: Failed in EAP select
(5)     [eap] = invalid
(5)   } # authenticate = invalid
(5) Failed to authenticate the user
(5) Using Post-Auth-Type Reject

I believe the problem is that $realm uninitialized but dont know why:
Use of uninitialized value $realm in hash element at /opt/freeradius-oauth2-perl/main.pm line 361

here is my /etc/freeradius/sites-enabled/inner-tunnel

server inner-tunnel {
listen {
        type = auth
        ipaddr = *
        port = 18120
}

authorize {

 if (!control:Auth-Type) {
              update control { Auth-Type := oauth2 }
}
}

authenticate {

Auth-Type oauth2 {
        oauth2
    }
}

post-auth {
}
}

**Comment by andisgithub** [comment]
Ubuntu 18.04.5 LTS
FreeRADIUS Version 3.0.21
This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi

**Comment by jimdigriz** [comment]
This is because you [did not follow the instructions](https://github.com/jimdigriz/freeradius-oauth2-perl#freeradius) correctly, they explain to *add* to the existing configure and do *not* tell you to strip everything away and leave only my module.

This particular error occurs as you removed the 'suffix' module.

Please revert back to the stock FR 'default'/'inner-tunnel' files and add the 'oauth2' hooks as described in the instructions. Once you have a working setup, then you can explore stripping parts of it away.

**Comment by andisgithub** [comment]
Thank you for quick answer and advice. I came to my stripped version while debugging, the same problem was with original inner-tunnel configuration updated acording instruction.

I reverted back, contents of inner-tunnel below

my discoveries so far

1) still the same problem uninitialized value $realm in hash element at /opt/freeradius-oauth2-perl/main.pm line 361
2) disabling update control { &Proxy-To-Realm := LOCAL } in authorize section does not help
3) without if (!control:Auth-Type) { update control {  Auth-Type := oauth2 } in authorize section request is not processed by oauth2 at all and reports (5)   ERROR: No Auth-Type found: rejecting the user via Post-Auth-Type = Reject



server inner-tunnel {
listen {
       ipaddr = 127.0.0.1
       port = 18120
       type = auth
}

authorize {
        filter_username
#       filter_inner_identity
        chap
        mschap
#       unix
#       IPASS
        suffix
#       ntdomain
        update control {
                &Proxy-To-Realm := LOCAL
        }
        eap { ok = return }
        files
        -sql
#       smbpasswd
        -ldap
        oauth2
#       daily
        expiration
        logintime
        pap

 if (!control:Auth-Type) {
              update control {
              Auth-Type := oauth2
           }
}
}


authenticate {
        Auth-Type PAP {
                pap
        }

        Auth-Type CHAP {
                chap
        }

        Auth-Type MS-CHAP {
                mschap
        }
        mschap
#       pam
#       Auth-Type LDAP {
#               ldap
#       }

        #
        #  Allow EAP authentication.
#       eap
#

 Auth-Type oauth2 {
        oauth2
    }
}

session {
        radutmp
#       sql
}

post-auth {
#       cui-inner
        #
#       update outer.session-state {
#              User-Name := &User-Name
#       }

#       reply_log
        -sql
#       ldap
        oauth2
#       moonshot_host_tid
#       moonshot_realm_tid
#       moonshot_coi_tid

        if (0) {
                update reply {
                        User-Name !* ANY
                        Message-Authenticator !* ANY
                        EAP-Message !* ANY
                        Proxy-State !* ANY
                        MS-MPPE-Encryption-Types !* ANY
                        MS-MPPE-Encryption-Policy !* ANY
                        MS-MPPE-Send-Key !* ANY
                        MS-MPPE-Recv-Key !* ANY
                }

                update {
                        &outer.session-state: += &reply:
                }
        }

        Post-Auth-Type REJECT {
                # log failed authentications in SQL, too.
                -sql
                attr_filter.access_reject

                #
                #  Let the outer session know which module failed, and why.
                #
                update outer.session-state {
                        &Module-Failure-Message := &request:Module-Failure-Message
                }
        }
}

pre-proxy {
#       files
#       attr_filter.pre-proxy
#       pre_proxy_log
}
post-proxy {
#       post_proxy_log
#       attr_filter.post-proxy
        eap
}

} # inner-tunnel server block

**Comment by jimdigriz** [comment]
Closing as I added https://github.com/jimdigriz/freeradius-oauth2-perl/commit/6344514a718e57e5968c3e5ede87a723e2eeb161 in response to this to try to shine light on when the config has been broken, and added some wording to the documentation.
