### ISSUE TITLE
Invalid scalar when not using default domain

### ISSUE THREAD

**Issue by MaximvanLuttikhuizen** [jimdigriz/freeradius-oauth2-perl#16]
Our Office365 tenant has a onmicrosoft.com primary domain and a number of vanity (secondary) domains.
Authenticating with an account with the domain.onmicrosoft.com upn-suffix works fine after the rather extensive list of users and groups is synced.

When we try to authenticate with an account user@domain.tld, authentication fails with:
Invalid value for shared scalar at /opt/freeradius-oauth2-perl/main.pm line 362.

I can get authentication to work for a while by changing %{Realm} in proxy.conf to domain.onmicrosoft.com restarting freeradius, change it back and restart again. Authentication then works for somewhere between an hour and a day after the lists ar synced. I haven't pinpointed the exact timeframe.

Before updating to the latest version of freeradius-oauth2-perl I had the same problem but then in the authorization section (line 334 in the latest release).

The value for $realm seems to be in order (log shows domain.tld when I place a line to output the value in main.pm) but %{$realms{$reams}} throws the error.

My proxy.conf (the lines starting with # are alternatives I tried):

realm domain.tld {
    oauth2 {
        discovery = "https://login.microsoftonline.com/%{Realm}/v2.0"
        #discovery = "https://login.microsoftonline.com/domain.onmicrosoft.com/v2.0"
        client_id = "My-clientID"
        client_secret = "My-clientSecret"
        cache_password = yes
        #cache_password = no
    }
}

realm domain.onmicrosoft.com {
    oauth2 {
        discovery = "https://login.microsoftonline.com/%{Realm}/v2.0"
        client_id = "My-clientID"
        client_secret = "My-clientSecret"
        cache_password = yes
    }
}

**Comment by jimdigriz** [comment]
Sounds like at least two bugs, sorry!

1. glancing at the code, looks like I forgot to add support for multiple realms going back to the same tenant (ie. AD directory); though (as you have done) duplicating the main domain config for each of the vanity domains should still work
1. for things to work and then start to fail after a few hours or a day seems strange, the DB refresh is ~30 seconds and the credentials cache is 10 days

A good place for us to start would be the [debugging output from FreeRADIUS (`freeradius -X | tee /tmp/debug`)](https://github.com/jimdigriz/freeradius-oauth2-perl#troubleshooting), which you can send to me directly at alex@coremem.com if you think you may miss redacting all the sensitive data in the output.

The [`debug = yes` option for the module](https://github.com/jimdigriz/freeradius-oauth2-perl#https-requests) may also help us work out what is going on here, though that definitely will include details you do not want pasted here.

**Comment by MaximvanLuttikhuizen** [comment]
Thanks for the quick reply. I send you the redacted logs.

**Comment by jimdigriz** [comment]
@MaximvanLuttikhuizen thanks for the debug, whilst spelunking through it and working out what is wrong, I see you are running the Debian/Ubuntu packaged version (3.0.16) so can you look to upgrading to trying a with version 3.0.21; I document [how to use the official Network RADIUS packages in the instructions](https://github.com/jimdigriz/freeradius-oauth2-perl#debianubuntu).

Also if you can test this on a bare bones install of FR (either in a VM or container) that would help separate the other changes in your configuration from this and make sure the problem is in my code; I see some per-realm switch logic and some eduroam goodness in there.

This bug does look strange on the face of it, as where it is complaining about the error, the code block just before should have made it impossible to occur. Can you paste here the contents of `/etc/os-release` and confirm the version of Perl being using by your OS (`perl -v`, for example I have v5.28.1).

Thanks

**Comment by MaximvanLuttikhuizen** [comment]
The file /etc/apt/trusted.gpg.d/networkradius.gpg.asc was present but empty. Obviously something went wrong there which I didn't notice. I upgraded freeradius to 3.0.21 but this did not solve the issue.

"This bug does look strange on the face of it, as where it is complaining about the error, the code block just before should have made it impossible to occur. "
Yes, that I found strange as well. The check if ${realms{$realm}} is present should prevent the error from occuring. This block is not present in "sub authenticate" however, only in "sub authorize". My knowledge of Perl is seriously lacking so I can't determine if it is possible that this variable can get overwritten or lost between these two subs.
I copied the code-block containing "unless (exists($realms{$realm})) {"  to the authorize sub. Now authentication works but as stated before, it might stop working after a while.

os-release: VERSION="18.04.5 LTS (Bionic Beaver)"
Perl version is 5.26.1

I will set-up an additional VM without the switches and eduroam stuff tomorrow
I will also monitor if authentication still works tomorrow.

**Comment by jimdigriz** [comment]
> Yes, that I found strange as well 

I think I have enough to replicate this at my end on my own, hopefully I will be able to get back to you in a few days.

> My knowledge of Perl is seriously lacking

Not a problem, bugs are my fault so leave that with me :)

> os-release: VERSION="18.04.5 LTS (Bionic Beaver)"
> Perl version is 5.26.1

A supported target, so no problem here.

> I will set-up an additional VM without the switches and eduroam stuff tomorrow

Thanks, this will help hugely to determine that something is not doing something unexpected outside the Perl module I did not cater for.

**Comment by MaximvanLuttikhuizen** [comment]
Set-up a clean VM and followed the instructions. This works as advertized.
The live server with the copied code snippet also still works.

I will let you know in a few days if this behaviour changes in any way.

**Comment by jimdigriz** [comment]
Make sure you keep a copy of the old configuration about, I would be interested in comparing the two to try to shed light on what happened; so I can document the problem or add a guard to the code to detect the situation. Thanks

**Comment by MaximvanLuttikhuizen** [comment]
Both servers still work so it is probably an issue with the site config files. I will fiddle around a bit with these to see if I can locate the source of the problem. Unfortunately this will have to wait till next week.

**Comment by jimdigriz** [comment]
Did you ever get to look at this or figure out what was happening?

**Comment by MaximvanLuttikhuizen** [comment]
@jimdigriz My apologies, I quite forgot I opened this issue. I never found out which setting caused the issue. As it is working on the cleanly installed VM, I am happy to declare this as pebkac and file it as closed.
