### ISSUE TITLE
More oauth2 Attributes in dictionary files

### ISSUE THREAD

**Issue by hoongooi12** [jimdigriz/freeradius-oauth2-perl#17]
Is there other any attributes we can query from Azure AD with freeradius-oauth2-perl?
i like to get other user / company info from Azure AD beside the OAuth2-Password-Last-Modified and OAuth2-Group?

**Comment by jimdigriz** [comment]
This should not really be done in `freeradius-oauth2-perl` (and outside its scope) you should write your own module (Perl or Python) to interact with https://docs.microsoft.com/en-us/graph/overview to get the information you want and present it to FR as attributes.

If you need me to help you with this then do reach out to me via my (paid) consultancy services info@coremem.com.

Google luck.
