### ISSUE TITLE
Radius assigned VLAN based on group membership in AzureAD

### ISSUE THREAD

**Issue by KeppensJonas** [jimdigriz/freeradius-oauth2-perl#19]
Hi

Is it possible to assign a specific VLAN to users based on their group membership in AzureAD?

Kind regards
Jonas

**Comment by jimdigriz** [comment]
Yes, I have pushed an *untested* example into the README at https://github.com/jimdigriz/freeradius-oauth2-perl#freeradius

Please can you tell me if they work for you.

**Comment by KeppensJonas** [comment]
I followed the guide for the EAP-TLS and this works with local user.
When I adjust the config for AzureAD and start Freeradius again I get this error:

/etc/freeradius/3.0/mods-enabled/oauth2[18]: Destination must be an attribute ref or a list
/etc/freeradius/3.0/mods-enabled/oauth2[12]: Instantiation failed for module "oauth2_cache"

**Comment by jimdigriz** [comment]
You seem to not be using the the Network RADIUS packaging for FreeRADIUS; it is clearly explained in the instructions that you must do so as well as how to use the correct packaging at https://github.com/jimdigriz/freeradius-oauth2-perl#preflight

If you want to use the distro provided options, then please contact me at info@coremem.com where we can discuss consultancy.

**Comment by KeppensJonas** [comment]
I followed the guide and added the Network RADIUS packaging but I got errors maybe because I'm trying it on Raspian on Raspberry Pi?

**Comment by jimdigriz** [comment]
> I followed the guide and added the Network RADIUS packaging but I got errors maybe because I'm trying it on Raspian on Raspberry Pi?

When you interact with *any* project, you should do with a sensitivity to that you are asking others to give you their free time for nothing in return.

You may want to run this project on a RPi but when you ran into problems your first step should have been to try to get it working as described in the instructions in a x86_64 VM where *supported* packaging is available to you; NR do *not* provide armel/armhf/AArch64 builds.

If you get that to work then great, try to replicate that success on your RPi...but be aware that any problems you have moving from x86 to ARM are only for you to solve; a *supported* option here as described in the instructions would have been to "compile from source the v3.0.x branch".

**Comment by jimdigriz** [comment]
Radio silence, closing.

Assuming until told otherwise the VLAN example works as it Works for Me(tm).
