### ISSUE TITLE
Need help with Azure Autenthication

### ISSUE THREAD

**Issue by Andimotz80** [jimdigriz/freeradius-oauth2-perl#20]
Hello,

I get the follwing error:
rlm_perl: oauth2 worker (test.co): supervisor started (tid=1)
rlm_perl: oauth2 worker (test.co): fetching discovery document
rlm_perl: oauth2 worker (test.co): discovery failed: 404 Not Found
Thread 1 terminated abnormally: discovery (test.co): 404 Not Found at /opt/freeradius-oauth2-perl/main.pm line 123.

my proxy.conf

realm test.co {
    oauth2 {
        discovery = "https://login.microsoftonline.com/8935a2f4-928c-4a2e-8997-686dbdf9047e/oauth2/v2.0/authorize"
        client_id = "...."
        client_secret = "..."
        cache_password = yes
    }
}

Can someone help me please

thanks

Andreas

**Comment by jimdigriz** [comment]
Your `discovery` URL is not correct, it looks like you went to the actual discovery URL and then selected the token authorization endpoint and used that.

You actually should have not changed it from it's original, `%{Realm}` is not a macro for you to replace, FreeRADIUS should do it for you. So as per the instructions, please put it back to:
```
discovery = "https://login.microsoftonline.com/%{Realm}/v2.0"
```

Alternatively you could use:
```
discovery = "https://login.microsoftonline.com/8935a2f4-928c-4a2e-8997-686dbdf9047e/v2.0"
```

**Comment by Andimotz80** [comment]
Hi,
now this works with radtest.

But when I try via uniquiti dream machine pro, I get the following errors:

(17) eap: Expiring EAP session with state 0x8c4d636e8b197a2f
(17) eap: Finished EAP session with state 0x8c4d636e8b197a2f
(17) eap: Previous EAP request found for state 0x8c4d636e8b197a2f, released from the list
(17) eap: Peer sent packet with method EAP PEAP (25)
(17) eap: Calling submodule eap_peap to process data
(17) eap_peap: Continuing EAP-TLS
(17) eap_peap: [eaptls verify] = ok
(17) eap_peap: Done initial handshake
(17) eap_peap: [eaptls process] = ok
(17) eap_peap: Session established.  Decoding tunneled attributes
(17) eap_peap: PEAP state send tlv failure
(17) eap_peap: Received EAP-TLV response
(17) eap_peap:   ERROR: The users session was previously rejected: returning reject (again.)
(17) eap_peap:   This means you need to read the PREVIOUS messages in the debug output
(17) eap_peap:   to find out the reason why the user was rejected
(17) eap_peap:   Look for "reject" or "fail".  Those earlier messages will tell you
(17) eap_peap:   what went wrong, and how to fix the problem
(17) eap: ERROR: Failed continuing EAP PEAP (25) session.  EAP sub-module failed
(17) eap: Sending EAP Failure (code 4) ID 84 length 4
(17) eap: Failed in EAP select
(17)     [eap] = invalid
(17)   } # authenticate = invalid
(17) Failed to authenticate the user
(17) Using Post-Auth-Type Reject
(17) # Executing group from file /etc/freeradius/3.0/sites-enabled/default
(17)   Post-Auth-Type REJECT {
(17) attr_filter.access_reject: EXPAND %{User-Name}
(17) attr_filter.access_reject:    --> test1234@asta.at
(17) attr_filter.access_reject: Matched entry DEFAULT at line 11
(17)     [attr_filter.access_reject] = updated
(17)     [eap] = noop
(17)     policy remove_reply_message_if_eap {
(17)       if (&reply:EAP-Message && &reply:Reply-Message) {
(17)       if (&reply:EAP-Message && &reply:Reply-Message)  -> FALSE
(17)       else {
(17)         [noop] = noop
(17)       } # else = noop
(17)     } # policy remove_reply_message_if_eap = noop
(17)   } # Post-Auth-Type REJECT = updated
(17) Delaying response for 1.000000 seconds
Waking up in 0.3 seconds.
Waking up in 0.1 seconds.

what shall I do?

Regards Andreas

**Comment by jimdigriz** [comment]
Not one line of debug mentions my Perl module here.

As described in the instructions, you should start with static username/password file (`users`) configuration, get that working for 802.1X so you become familiar with the moving parts, and *after* that works, then look to use the Perl module.

Sorry I am unable to provide pro bono consultancy work for your organisation.
