### ISSUE TITLE
Unifi freeradius authentication.

### ISSUE THREAD

**Issue by iovcho** [jimdigriz/freeradius-oauth2-perl#22]
Hello all. I setup freeradius + oauth2 with Microsoft and works great. I have issue with unifi wifi router, because they support only MSCHAP protocol, but freeradius-oauth2 use EAP-TTLS/PAP . Can you help how can connect unifi to use freeradius-oauth2 for authentication ? Any suggestions are welcome.

**Comment by jimdigriz** [comment]
Sorry, but I do not support third party vendor hardware (for free). I would recommend you speak with your supplier, you did pay them after all.

If you wish to explore (paid) help from me, [please contact my consultancy](https://github.com/jimdigriz/freeradius-oauth2-perl#support).
