### ISSUE TITLE
<EAP MSCHAPV2

### ISSUE THREAD

**Issue by AfBrainPlus** [jimdigriz/freeradius-oauth2-perl#26]
How can I get the system to work with MSCHAPV2?

**Comment by jimdigriz** [comment]
From literally the second paragraph of the readme...

> you must use [EAP-TTLS/PAP](https://en.wikipedia.org/wiki/Extensible_Authentication_Protocol#EAP_Tunneled_Transport_Layer_Security_(EAP-TTLS))

You can't, also why would you want to? MSCHAPv2 is practically no more secure than PAP.

**Comment by AfBrainPlus** [comment]
It’s needed for our VPN on Ubiquiti UniFi Udm Pro

<http://www.facebook.com/brain.plus.training>

Yours sincerely / Med venlig hilsen
Asger Frisgård
QA Specialist and IT administrator

(+45) 53 63 02 89

BRAIN+ A/S
Købmagergade 53, third floor
DK-1150 Copenhagen K

www.brain-plus.com
www.twitter.com/TheBrainPlus
www.facebook.com/brain.plus.training<http://www.facebook.com/brain.plus.training>
<https://aka.ms/o0ukef>
________________________________
Fra: Alexander Clouter ***@***.***>
Sendt: Monday, June 13, 2022 10:28:51 PM
Til: jimdigriz/freeradius-oauth2-perl ***@***.***>
Cc: Asger Frisgård ***@***.***>; Author ***@***.***>
Emne: Re: [jimdigriz/freeradius-oauth2-perl] <EAP MSCHAPV2 (Issue #26)


From literally the second paragraph of the readme...

you must use EAP-TTLS/PAP<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FExtensible_Authentication_Protocol%23EAP_Tunneled_Transport_Layer_Security_(EAP-TTLS)&data=05%7C01%7Caf%40brain-plus.com%7Ccf74492c750b4088201008da4d7b5493%7Cf2f9babfec61480d81d3c163d28ca06a%7C0%7C0%7C637907489339429350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8MWw1tYw5QhrFFJ5dPEdlGGb0Tb26NI%2FdADAqi3chXg%3D&reserved=0>

You can't, also why would you want to? MSCHAPv2 is practically no more secure than PAP.

**Comment by jimdigriz** [comment]
You probably should speak to Ubiquiti on how to make their VPN work with PAP, you did pay them for the equipment and support. Good luck!
