### ISSUE TITLE
freeradius-oauth2-perl with NAC Alcasar

### ISSUE THREAD

**Issue by scoude** [jimdigriz/freeradius-oauth2-perl#29]
Hi,
I don't think this is a bug, but I can't understand why the module doesn't seem to take into account my "realm" with the freeradius 3.0.22 used in the NAC Alcasar (https://alcasar.net /).
In debug mode, the module seems to be loaded:

```
/usr/sbin/radiusd -Xd /etc/raddb/ | grep oauth2
including configuration file /etc/raddb//mods-enabled/oauth2
including configuration file /etc/raddb//policy.d/oauth2
  # Creating Auth-Type = oauth2
   # Loading module "oauth2_perl" from file /etc/raddb//mods-enabled/oauth2
   perl oauth2_perl {
         filename = "/opt/freeradius-oauth2-perl/main.pm"
   # Loading module "oauth2_cache" from file /etc/raddb//mods-enabled/oauth2
   cache oauth2_cache {
   # Instantiating module "oauth2_perl" from file /etc/raddb//mods-enabled/oauth2
rlm_perl:********************************************* oauth2 global* ************************************************** *
   # Instantiating module "oauth2_cache" from file /etc/raddb//mods-enabled/oauth2
rlm_cache (oauth2_cache): Driver rlm_cache_rbtree (module rlm_cache_rbtree) loaded and linked
Compiling Auth-Type oauth2 for attr Auth-Type
```

But at the time of the test, here is what it gives:

```
> (0) policy oauth2.authorize {
> (0) if (&Realm && &User-Password && "%{config:realm[%{Realm}].oauth2.discovery}") {
> (0) if (&Realm && &User-Password && "%{config:realm[%{Realm}].oauth2.discovery}") -> FALSE
> (0) } # policy oauth2.authorize = noop
```

I tested the installation of the module on a Debian 11 machine with freeradius, it works well, I authenticate well with an email and a password on Office365!
I took the same configurations in the Alcasar freeradius but it doesn't seem to "hang" my "realm"!
Help please!

**Comment by keitatie** [comment]
Bonjour; 
j'espère que vous allez bien. Avez-vous trouvé une solution à ce sujet? j'ai le même problème que vous. 

Merci d'avancer pour votre aide.

**Comment by jimdigriz** [comment]
There is not enough debugging to work from here, I am not really sure what I am expected to do?

As described in the ['support' section](https://github.com/jimdigriz/freeradius-oauth2-perl#support) I need the output of `freeradius -X` not just the bits *you* think are important.

Sorry, going to close this as there is not enough to work on to help.

Do re-open the ticket if you have debugging logs to offer.
