### ISSUE TITLE
MSCHAPv2 support

### ISSUE THREAD

**Issue by jimdigriz** [jimdigriz/freeradius-oauth2-perl#3]
>Alexander,
>
>Currently I am working on a project to authenticate users on eduroam-wifi using their Office 365 >credentials. I found your oauth2-perl scripts on github and implemented it on my freeradius server.
>This works great for iOS devices but not for Windows devices. Information on this is sparse and I am by >no means a master in configuring radius. I thought that maybe you can give me a pointer.
>
>I traced the problem to the authentication section of the inner tunnel. MS insist on using Auth-Type ms->chapv2 where my iPad uses gtc. I have added oauth2-perl to the MS-CHAP section. The perl-script >connects to Azure but returns the error: "rlm_perl: Added pair Reply-Message = AADSTS90014: The >request body must contain the following parameter: 'password'."
>
>Any help is greatly appreciated.
>
>With kind regards,
>Met vriendelijke groet,
>
>Maxim van Luttikhuizen
>Dienst- en productontwikkeling

>Alexander,
>
> Thanks for the quick response, I missed the sentence about ttls/pap. I use Windows 8.1 and can configure to use pap. This will then succesfully authorize but not authenticate because there is no auth-type after the oauth2-perl module has finished. (using the iPad auth-type= EAP).
>I solved this by adding the following to the authorize section of the inner-tunnel:
>
>                 if (!control:Auth-Type) {
>                   update control {
>                   Auth-Type := oauth2-perl
>                }
>
> can now authenticate with both iOS and windows 8.1 based computers.
>
> Met vriendelijke groet,
>
> Maxim van Luttikhuizen
> Dienst- en productontwikkeling

**Comment by jimdigriz** [comment]
Soon to be released new branch https://github.com/jimdigriz/freeradius-oauth2-perl/tree/fr3 changes this all.

Glad you were able to resolve the problem yourself, hopefully my new work does not exhibit this! :)

**Comment by kdkavanagh** [comment]
With the new version, what is the recommended way to enable MSCHAPv2?  Same as above?

**Comment by jimdigriz** [comment]
The [password grant *requires* that the cleartext password](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc#authorization-request) is supplied. Password grant has *always* been used by this project, both the older version and the current one, the token URL is the same.

As MSCHAPv2 does not provide User-Password in the request, it is impossible to use the password grant.

If you look at the `radiusd -X` output, you will see the password in cleartext being used and MSCHAPv2 not being used.
