### ISSUE TITLE
Issues with reaching AzureAD

### ISSUE THREAD

**Issue by NickiUrwinIT** [jimdigriz/freeradius-oauth2-perl#32]
Morning all, 

I have followed this documentation down to the letter and when running a RADTEST i get the following error:

Sent Access-Request Id 59 from 0.0.0.0:53094 to 127.0.0.1:1812 length 109
        User-Name = "nicki.urwin@*****co.uk"
        User-Password = "*********"
        NAS-IP-Address = **.**.**.**
        NAS-Port = 0
        Message-Authenticator = 0x00
        Cleartext-Password = "********"
(0) No reply from server for ID 59 socket 3

Guessing its the link between AzureAD and the EC2 instance.

Any ideas please?

**Comment by jimdigriz** [comment]
Have a read of https://github.com/jimdigriz/freeradius-oauth2-perl#support and get back to me.

**Comment by NickiUrwinIT** [comment]
Tried from another session:

Sent Access-Request Id 43 from 0.0.0.0:44116 to 127.0.0.1:1812 length 109
        User-Name = "nicki.urwin@*****co.uk"
        User-Password = "**********"
        NAS-IP-Address = **.**.**.**
        NAS-Port = 0
        Message-Authenticator = 0x00
        Cleartext-Password = "*********"
Received Access-Reject Id 43 from 127.0.0.1:1812 to 127.0.0.1:44116 length 20
(0) -: Expected Access-Accept got Access-Reject

**Comment by NickiUrwinIT** [comment]
> Have a read of https://github.com/jimdigriz/freeradius-oauth2-perl#support and get back to me.
> 
> There is very little for me to work (full debug output?) with here as all I see is "does not work".
> 
> You mention AzureAD and EC2, but I see the RADIUS packet destination is `localhost` (`127.0.0.1`).
> 
> I have no idea what you are doing. Sorry.

This is showing for a local LDAP server not AzureAD.

**Comment by jimdigriz** [comment]
> This is showing for a local LDAP server not AzureAD.

...how would I know this from your original message in https://github.com/jimdigriz/freeradius-oauth2-perl/issues/32#issue-1593305010

There you say:

"I have followed this documentation down to the letter..."

LDAP is not used anywhere by this project. If you have access to LDAP, you do not need this module.
