### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by NickUrwin** [jimdigriz/freeradius-oauth2-perl#33]
Following documentation and hitting a brick wall with the following commands and errors:

Command:

printf '\n$INCLUDE /opt/freeradius-oauth2-perl/dictionary\n' >> /etc/freeradius/dictionary
ln -s /opt/freeradius-oauth2-perl/module /etc/freeradius/mods-enabled/oauth2
ln -s /opt/freeradius-oauth2-perl/policy /etc/freeradius/policy.d/oauth2

Error:

ln: failed to create symbolic link '/etc/freeradius/mods-enabled/oauth2': No such file or directory
ln: failed to create symbolic link '/etc/freeradius/policy.d/oauth2': No such file or directory

Any ideas at all?

**Comment by jimdigriz** [comment]
My guess is:
 * you used the Ubuntu/Debian/distro provided versions of FreeRADIUS which install configuration files to `/etc/freeradius/3.0/...`
 * you have installed from source, which is fine but the configuration files are (if I remember correctly) at `/usr/local/raddb/etc/...`

You either need to use the NetworkRADIUS provided packaging as my instructions [politely ask you to use](https://github.com/jimdigriz/freeradius-oauth2-perl#support) and then go on to [describe how to use those packages](https://github.com/jimdigriz/freeradius-oauth2-perl#debianubuntu).

Those compiling and installing from source will need to adjust the instructions depending on where they have configure the build process to store configuration files.

**Comment by NickUrwin** [comment]
Looks like I missed some steps. Sorry for wasting your time. I am on 22.04 so need to download the jammy version.

Thanks in advance.

**Comment by jimdigriz** [comment]
There are builds for Ubuntu 22.04 provided by NetworkRADIUS at https://networkradius.com/packages/#fr32-ubuntu

Version 3.2.x of FreeRADIUS should work, if not, it is a bug I need to fix.
