### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by senseyk-git** [jimdigriz/freeradius-oauth2-perl#36]
hi,
thank you for this knowledge sharing.

i follow the steps but when i try to do the first restarst after configuring the AAA part with the code provide i got this:

`
May 15 21:18:51 FreeRadius freeradius[7033]: FreeRADIUS Version 3.2.2
May 15 21:18:51 FreeRadius freeradius[7033]: Copyright (C) 1999-2022 The FreeRADIUS server project and contributors
May 15 21:18:51 FreeRadius freeradius[7033]: There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
May 15 21:18:51 FreeRadius freeradius[7033]: PARTICULAR PURPOSE
May 15 21:18:51 FreeRadius freeradius[7033]: You may redistribute copies of FreeRADIUS under the terms of the
May 15 21:18:51 FreeRadius freeradius[7033]: GNU General Public License
May 15 21:18:51 FreeRadius freeradius[7033]: For more information about these matters, see the file named COPYRIGHT
May 15 21:18:51 FreeRadius freeradius[7033]: Starting - reading configuration files ...
May 15 21:18:51 FreeRadius freeradius[7033]: Errors reading /etc/freeradius/dictionary: dict_init: /etc/freeradius/dictionary[51]: Couldn't open dictionary "/opt/freeradius-oauth2-perl/dictionary": No such file or directory
`

i first start by copy the project https://github.com/jimdigriz/freeradius-oauth2-perl.git then i see that someone has the same type of issue than me. so restart from scratch but that time i copy from here https://github.com/FreeRADIUS/freeradius-server.git, but same error.

can you help me please ?

Best Regards
thank you

**Comment by jimdigriz** [comment]
[First commands you type in the Preflight section](https://github.com/jimdigriz/freeradius-oauth2-perl#preflight), you copied the project to the wrong place, it is meant to be in `/opt`.

If you want it elsewhere you will need to adjust all the paths of the project and the config files to match.
