### ISSUE TITLE
Did they change something in Azure AD that makes this no longer work?

### ISSUE THREAD

**Issue by dagentooboy** [jimdigriz/freeradius-oauth2-perl#41]
I have followed the instructions very carefully. I thought I had the application configured correctly but it keeps returning notfound for my user. I am sure I messed up something simple but I can't seem to figure it out.

Any guidance on a direction would be a big help. 

[radiusd.log](https://github.com/jimdigriz/freeradius-oauth2-perl/files/12566066/radiusd.log)

**Comment by dagentooboy** [comment]
Never mind I finally figured it out. Turns out the person that created my account and I used a different number of capital letters. 

I added lc() to the lines dealing with username like so.
`lc($RAD_REQUEST{'User-Name'})`

And I did lc() on this line. That should make everything not case sensitive for username.

`                                                  $r->{n} = lc($d->{userPrincipalName}) if (exists($d->{userPrincipalName}));
`

Here is the edited file. 
[main.txt](https://github.com/jimdigriz/freeradius-oauth2-perl/files/12566321/main.txt)

**Comment by jimdigriz** [comment]
Glad you worked it out. Thanks for updating the issue!

As a suggestion, I would recommend you use `unlang` to do this, in your `authorize` section just after `preprocess` use something like:
```
update request {
    &User-Name := "%{tolower:User-Name}"
}
```

You may wish to also consider looking at [`raddb/policy.d/filter`](https://github.com/FreeRADIUS/freeradius-server/blob/v3.2.x/raddb/policy.d/filter) to catch other funny business too; though your mileage may vary.
